package standard_library

// ###############################################
// # This file is generated via code-generation. #
// # Check gen.go                                #
// ###############################################

var Functions = map[string]Function{
"tenecs_array_append": tenecs_array_append(),
"tenecs_array_filter": tenecs_array_filter(),
"tenecs_array_flatMap": tenecs_array_flatMap(),
"tenecs_array_fold": tenecs_array_fold(),
"tenecs_array_forEach": tenecs_array_forEach(),
"tenecs_array_length": tenecs_array_length(),
"tenecs_array_map": tenecs_array_map(),
"tenecs_array_mapNotNull": tenecs_array_mapNotNull(),
"tenecs_array_repeat": tenecs_array_repeat(),
"tenecs_boolean_and": tenecs_boolean_and(),
"tenecs_boolean_not": tenecs_boolean_not(),
"tenecs_boolean_or": tenecs_boolean_or(),
"tenecs_compare_eq": tenecs_compare_eq(),
"tenecs_http_newServer": tenecs_http_newServer(),
"tenecs_int_minus": tenecs_int_minus(),
"tenecs_int_plus": tenecs_int_plus(),
"tenecs_int_times": tenecs_int_times(),
"tenecs_json_JsonError": tenecs_json_JsonError(),
"tenecs_json_field": tenecs_json_field(),
"tenecs_json_parseArray": tenecs_json_parseArray(),
"tenecs_json_parseBoolean": tenecs_json_parseBoolean(),
"tenecs_json_parseInt": tenecs_json_parseInt(),
"tenecs_json_parseObject0": tenecs_json_parseObject0(),
"tenecs_json_parseObject1": tenecs_json_parseObject1(),
"tenecs_json_parseObject10": tenecs_json_parseObject10(),
"tenecs_json_parseObject11": tenecs_json_parseObject11(),
"tenecs_json_parseObject12": tenecs_json_parseObject12(),
"tenecs_json_parseObject13": tenecs_json_parseObject13(),
"tenecs_json_parseObject14": tenecs_json_parseObject14(),
"tenecs_json_parseObject15": tenecs_json_parseObject15(),
"tenecs_json_parseObject16": tenecs_json_parseObject16(),
"tenecs_json_parseObject17": tenecs_json_parseObject17(),
"tenecs_json_parseObject18": tenecs_json_parseObject18(),
"tenecs_json_parseObject19": tenecs_json_parseObject19(),
"tenecs_json_parseObject2": tenecs_json_parseObject2(),
"tenecs_json_parseObject20": tenecs_json_parseObject20(),
"tenecs_json_parseObject21": tenecs_json_parseObject21(),
"tenecs_json_parseObject22": tenecs_json_parseObject22(),
"tenecs_json_parseObject3": tenecs_json_parseObject3(),
"tenecs_json_parseObject4": tenecs_json_parseObject4(),
"tenecs_json_parseObject5": tenecs_json_parseObject5(),
"tenecs_json_parseObject6": tenecs_json_parseObject6(),
"tenecs_json_parseObject7": tenecs_json_parseObject7(),
"tenecs_json_parseObject8": tenecs_json_parseObject8(),
"tenecs_json_parseObject9": tenecs_json_parseObject9(),
"tenecs_json_parseOr": tenecs_json_parseOr(),
"tenecs_json_parseString": tenecs_json_parseString(),
"tenecs_json_toJson": tenecs_json_toJson(),
"tenecs_string_endsWith": tenecs_string_endsWith(),
"tenecs_string_join": tenecs_string_join(),
"tenecs_string_startsWith": tenecs_string_startsWith(),
}
