package standard_library

// ###############################################
// # This file is generated via code-generation. #
// # Check gen.go                                #
// ###############################################

var Functions = map[string]Function{
"tenecs_array_append": tenecs_array_append(),
"tenecs_array_filter": tenecs_array_filter(),
"tenecs_array_flatMap": tenecs_array_flatMap(),
"tenecs_array_fold": tenecs_array_fold(),
"tenecs_array_forEach": tenecs_array_forEach(),
"tenecs_array_length": tenecs_array_length(),
"tenecs_array_map": tenecs_array_map(),
"tenecs_array_mapNotNull": tenecs_array_mapNotNull(),
"tenecs_array_repeat": tenecs_array_repeat(),
"tenecs_boolean_and": tenecs_boolean_and(),
"tenecs_boolean_not": tenecs_boolean_not(),
"tenecs_boolean_or": tenecs_boolean_or(),
"tenecs_compare_eq": tenecs_compare_eq(),
"tenecs_error_error": tenecs_error_error(),
"tenecs_http_newServer": tenecs_http_newServer(),
"tenecs_int_minus": tenecs_int_minus(),
"tenecs_int_plus": tenecs_int_plus(),
"tenecs_int_times": tenecs_int_times(),
"tenecs_json_JsonField": tenecs_json_JsonField(),
"tenecs_json_jsonArray": tenecs_json_jsonArray(),
"tenecs_json_jsonBoolean": tenecs_json_jsonBoolean(),
"tenecs_json_jsonInt": tenecs_json_jsonInt(),
"tenecs_json_jsonObject0": tenecs_json_jsonObject0(),
"tenecs_json_jsonObject1": tenecs_json_jsonObject1(),
"tenecs_json_jsonObject10": tenecs_json_jsonObject10(),
"tenecs_json_jsonObject11": tenecs_json_jsonObject11(),
"tenecs_json_jsonObject12": tenecs_json_jsonObject12(),
"tenecs_json_jsonObject13": tenecs_json_jsonObject13(),
"tenecs_json_jsonObject14": tenecs_json_jsonObject14(),
"tenecs_json_jsonObject15": tenecs_json_jsonObject15(),
"tenecs_json_jsonObject16": tenecs_json_jsonObject16(),
"tenecs_json_jsonObject17": tenecs_json_jsonObject17(),
"tenecs_json_jsonObject18": tenecs_json_jsonObject18(),
"tenecs_json_jsonObject19": tenecs_json_jsonObject19(),
"tenecs_json_jsonObject2": tenecs_json_jsonObject2(),
"tenecs_json_jsonObject20": tenecs_json_jsonObject20(),
"tenecs_json_jsonObject21": tenecs_json_jsonObject21(),
"tenecs_json_jsonObject22": tenecs_json_jsonObject22(),
"tenecs_json_jsonObject3": tenecs_json_jsonObject3(),
"tenecs_json_jsonObject4": tenecs_json_jsonObject4(),
"tenecs_json_jsonObject5": tenecs_json_jsonObject5(),
"tenecs_json_jsonObject6": tenecs_json_jsonObject6(),
"tenecs_json_jsonObject7": tenecs_json_jsonObject7(),
"tenecs_json_jsonObject8": tenecs_json_jsonObject8(),
"tenecs_json_jsonObject9": tenecs_json_jsonObject9(),
"tenecs_json_jsonOr": tenecs_json_jsonOr(),
"tenecs_json_jsonString": tenecs_json_jsonString(),
"tenecs_string_endsWith": tenecs_string_endsWith(),
"tenecs_string_join": tenecs_string_join(),
"tenecs_string_startsWith": tenecs_string_startsWith(),
}
